[package]
name = "bisync_macros"
description = "macro implementations for the bisync crate"
license = "MIT OR Apache-2.0"
version = "0.2.3"
edition = "2021"
repository = "https://github.com/JM4ier/bisync"

[lib]
proc-macro = true

[dependencies]
